### ISSUE TITLE
System hangs on Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by stefanolande** [szpajder/RTLSDR-Airband#101]
Hello,
I am running rtl_airband on a Raspberry Pi 3 B+.
After a few minutes the system becomes unresponsive for some time , then responsive again, and so on.
Sometime the system hangs altogether, forcing me to do an hard reset.
I tried to lower the sampling rate to 0.5 MHz and the FFT size to 256 with no results.

I am running librtlsdr-dev version 0.5.3-11, and libusb version 1.0.21-1.
Any idea on how I can troubleshoot this issue?

**Comment by szpajder** [comment]
Power problems?

See here: https://github.com/szpajder/RTLSDR-Airband/issues/94

**Comment by stefanolande** [comment]
The power supply is rated 3A. Maybe it's of poor quality.

**Comment by szpajder** [comment]
It's not only about power supply but also about the cable connecting it to the Pi.

Verify all steps from this list: https://github.com/szpajder/RTLSDR-Airband/issues/94#issuecomment-403890481

**Comment by stefanolande** [comment]
Closing because it is most likely not a software issue. Thank you for your help.
