### ISSUE TITLE
maximum number of dongles on Rpi3 ?

### ISSUE THREAD

**Issue by mhaberler** [szpajder/RTLSDR-Airband#105]
Raspberry Pi 3 Model B Rev 1.2 here, 2 well-powered 4-port USB hubs.

- running rtl_test with default options: maximum number of dongles without failure = 4
- running rtl_test with -S (sync mode) - 8 dongle on 2 hubs: no problem

am I safe running rtl_airband with more than 4 dongles?

thanks, Michael

**Comment by szpajder** [comment]
With default settings - no.

With fft_size and sampling rate reduced by half and with NFM support
disabled - possibly, but you'll be at the edge of GPU performance (read:
choppy audio).

**Comment by mhaberler** [comment]
thanks! appreciated.

Great job on this project!

best regards, Michael
