### ISSUE TITLE
unknown output type

### ISSUE THREAD

**Issue by trcyprkr** [szpajder/RTLSDR-Airband#114]
the problem i am having is "unknown output type" . Here's my config:

devices:
({
type = "rtlsdr";
index = 0;
gain = 25;
correction = 80;
mode = "scan";
channels:
(
{
freqs = ( 118150000, 124750000, 134425000, 134475000, 128175000 );
labels = ( "Tower", "Ground", "Approach", "other", "other" );
modulation = "am";
outputs:
(
{
type = "pulse";
server = "127.0.0.1";
sink = "default";
stream_name = "De Planes";
continuous = false;
}
);
}
);
}
);

**Comment by szpajder** [comment]
You didn't enable Pulseaudio support when compiling the program.

**Comment by trcyprkr** [comment]
ok, i'll do it again just to make sure.  thanks
