### ISSUE TITLE
Crash or enter loop with USBDEVFS_DISCARDURB

### ISSUE THREAD

**Issue by dropdrop20** [szpajder/RTLSDR-Airband#117]
It crashes or enter infinte loop. See strace output. 

os: raspbian
SoapySDR + SoapySDRPlay 0.8, up to date 13.03.2019

root@xxxxxxx~ # head /usr/local/etc/rtl_airband.conf
devices:
({
  type = "soapysdr";
  #device_string = "driver=sdrplay,device_id=0";
  device_string = "driver=sdrplay";
  index = 0;
  gain = 25;
  centerfreq = 146.0;

root@xxxxxxx:~ # rtl_airband -fe
SoapySDR: device 'driver=sdrplay': using native sample format 'CS16' (fullScale=32767.0)
RTLSDR-Airband version v3.0.1 starting

strace -fp 828
[pid   840] ioctl(10, USBDEVFS_DISCARDURB, 0x696938c0) = -1 EINVAL (Invalid argument)
[pid   840] ioctl(10, USBDEVFS_DISCARDURB, 0x69693894) = -1 EINVAL (Invalid argument)
[pid   840] ioctl(10, USBDEVFS_DISCARDURB, 0x69693868) = -1 EINVAL (Invalid argument)
[..]
[pid   840] ioctl(10, USBDEVFS_DISCARDURB, 0x69693868) = -1 EINVAL (Invalid argument)

root@pafos:~ # ldd `which rtl_airband`
	linux-vdso.so.1 (0x7ece5000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76f98000)
	librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0x76f64000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76f51000)
	libvorbisenc.so.2 => /usr/lib/arm-linux-gnueabihf/libvorbisenc.so.2 (0x76ebf000)
	libmp3lame.so.0 => /usr/lib/arm-linux-gnueabihf/libmp3lame.so.0 (0x76e46000)
	libshout.so.3 => /usr/lib/arm-linux-gnueabihf/libshout.so.3 (0x76e2f000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76e06000)
	libconfig++.so.9 => /usr/lib/arm-linux-gnueabihf/libconfig++.so.9 (0x76de4000)
	libbcm_host.so => /opt/vc/lib/libbcm_host.so (0x76dbd000)
	librtlsdr.so.0 => /usr/lib/arm-linux-gnueabihf/librtlsdr.so.0 (0x76da0000)
	libSoapySDR.so.0.8 => /usr/local/lib/libSoapySDR.so.0.8 (0x76d3c000)
	libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x76bf4000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76b75000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76b48000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76a09000)
	/lib/ld-linux-armhf.so.3 (0x76fae000)
	libvorbis.so.0 => /usr/lib/arm-linux-gnueabihf/libvorbis.so.0 (0x769d2000)
	libogg.so.0 => /usr/lib/arm-linux-gnueabihf/libogg.so.0 (0x769c4000)
	libtheora.so.0 => /usr/lib/arm-linux-gnueabihf/libtheora.so.0 (0x7696f000)
	libspeex.so.1 => /usr/lib/arm-linux-gnueabihf/libspeex.so.1 (0x76949000)
	libvchiq_arm.so => /opt/vc/lib/libvchiq_arm.so (0x76933000)
	libvcos.so => /opt/vc/lib/libvcos.so (0x7691a000)
	libusb-1.0.so.0 => /lib/arm-linux-gnueabihf/libusb-1.0.so.0 (0x768f5000)
	libcairo.so.2 => /usr/lib/arm-linux-gnueabihf/libcairo.so.2 (0x76804000)
	libudev.so.1 => /lib/arm-linux-gnueabihf/libudev.so.1 (0x767e7000)
	libpixman-1.so.0 => /usr/lib/arm-linux-gnueabihf/libpixman-1.so.0 (0x76745000)
	libfontconfig.so.1 => /usr/lib/arm-linux-gnueabihf/libfontconfig.so.1 (0x76702000)
	libfreetype.so.6 => /usr/lib/arm-linux-gnueabihf/libfreetype.so.6 (0x76667000)
	libpng16.so.16 => /usr/lib/arm-linux-gnueabihf/libpng16.so.16 (0x7662d000)
	libxcb-shm.so.0 => /usr/lib/arm-linux-gnueabihf/libxcb-shm.so.0 (0x7661a000)
	libxcb.so.1 => /usr/lib/arm-linux-gnueabihf/libxcb.so.1 (0x765eb000)
	libxcb-render.so.0 => /usr/lib/arm-linux-gnueabihf/libxcb-render.so.0 (0x765d0000)
	libXrender.so.1 => /usr/lib/arm-linux-gnueabihf/libXrender.so.1 (0x765b7000)
	libX11.so.6 => /usr/lib/arm-linux-gnueabihf/libX11.so.6 (0x76494000)
	libXext.so.6 => /usr/lib/arm-linux-gnueabihf/libXext.so.6 (0x76475000)
	libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0x7644e000)
	libexpat.so.1 => /lib/arm-linux-gnueabihf/libexpat.so.1 (0x7641c000)
	libXau.so.6 => /usr/lib/arm-linux-gnueabihf/libXau.so.6 (0x76411000)
	libXdmcp.so.6 => /usr/lib/arm-linux-gnueabihf/libXdmcp.so.6 (0x763fc000)
	libbsd.so.0 => /lib/arm-linux-gnueabihf/libbsd.so.0 (0x763d3000)

**Comment by szpajder** [comment]
See here: https://github.com/szpajder/RTLSDR-Airband/issues/116#issuecomment-472607225

Please update SoapySDR and test again.
