### ISSUE TITLE
Sample rates for Scan mode?

### ISSUE THREAD

**Issue by Strykar** [szpajder/RTLSDR-Airband#118]
I have an RSP2, what should my sample rates be for Scan mode on AM? I'm experiencing clipping and noise.

**Comment by szpajder** [comment]
The default rate will do, unless your computer is very weak.

If a particular sample rate works well in multichannel mode, it will work equally well in scan mode, there is no difference.

**Comment by Strykar** [comment]
This is on an Odroid C2 which does nothing else and is chilling all cores at 500Mhz.

**Comment by szpajder** [comment]
So lower it down and see if it works better. Simple.
