### ISSUE TITLE
Writing to a new file instead of appending/overwriting?

### ISSUE THREAD

**Issue by simonepsp** [szpajder/RTLSDR-Airband#125]
Hi! I'm currently using this project to record from multiple channels (/w multiple sdr devices) and it's working great.
Also I find the whole subject around it fascinating.... :)

I'm just wondering if it's possible to save a new file after every silence (when squelch is closed) instead of appending/overwriting the same file.

Format would be CHANNELNAME_STARTDATETIME.mp3
For example:

-- NAME_04292019_0750.mp3
-- NAME_04292019_0813.mp3
-- NAME_04292019_0819.mp3

Hope that's clear.
Thanks for your help!
Simon

**Comment by szpajder** [comment]
This feature is not currently supported but it's been requested and is tracked here: https://github.com/szpajder/RTLSDR-Airband/issues/59 .
