### ISSUE TITLE
Feature Request: scanning metadata tag

### ISSUE THREAD

**Issue by redrob** [szpajder/RTLSDR-Airband#129]
For scan mode metadata, it would be great to see a 'Scanning...' metadata tag for when RTLSDR-Airband is actively scanning and not stopped on a channel. This is a common, editable feature in other icecast/shoutcast clients which support dynamic scanner metadata. 

Currently, icecast will continue to show the last stopped on channel/alpha tag while scanning until it stops on a new channel.

Much appreciated.

**Comment by dupilax** [comment]
By that you mean it could be possible to see on Icecast wich frequency is active ?!

**Comment by szpajder** [comment]
This has already been requested. I don't think it's a good idea, see
https://github.com/szpajder/RTLSDR-Airband/issues/104#issuecomment-441102090
