### ISSUE TITLE
Error while parsing configuration file

### ISSUE THREAD

**Issue by M0CRT** [szpajder/RTLSDR-Airband#13]
Hi
New installation on Gentoo x64

Strange issue.  Upon running the built application, I receive a,

'Error while parsing configuration file /usr/local/etc/rtl_airband.conf line 284: syntax error.'

Default configuration file (not edited).

Any ideas?

Thanks

STRACE -f :

execve("./rtl_airband", ["./rtl_airband"], [/* 63 vars */]) = 0
brk(0)                                  = 0x2422000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2096c1f000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=270010, ...}) = 0
mmap(NULL, 270010, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f2096bdd000
close(3)                                = 0
open("/lib64/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240!\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=27440, ...}) = 0
mmap(NULL, 2124768, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f20967f9000
mprotect(0x7f20967ff000, 2093056, PROT_NONE) = 0
mmap(0x7f20969fe000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5000) = 0x7f20969fe000
close(3)                                = 0
open("/usr/lib64/libvorbisenc.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360:\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=665648, ...}) = 0
mmap(NULL, 2760880, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2096556000
mprotect(0x7f20965e0000, 2097152, PROT_NONE) = 0
mmap(0x7f20967e0000, 102400, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8a000) = 0x7f20967e0000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2096bdc000
open("/usr/lib64/libmp3lame.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \237\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=245280, ...}) = 0
mmap(NULL, 2530224, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f20962ec000
mprotect(0x7f2096326000, 2097152, PROT_NONE) = 0
mmap(0x7f2096526000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3a000) = 0x7f2096526000
mmap(0x7f2096528000, 187312, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f2096528000
close(3)                                = 0
open("/usr/lib64/libshout.so.3", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220V\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=64680, ...}) = 0
mmap(NULL, 2160208, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f20960dc000
mprotect(0x7f20960eb000, 2093056, PROT_NONE) = 0
mmap(0x7f20962ea000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe000) = 0x7f20962ea000
close(3)                                = 0
open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\r`\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=93624, ...}) = 0
mmap(NULL, 2204944, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2095ec1000
mprotect(0x7f2095ed7000, 2093056, PROT_NONE) = 0
mmap(0x7f20960d6000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x7f20960d6000
mmap(0x7f20960d8000, 13584, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f20960d8000
close(3)                                = 0
open("/usr/lib64/librtlsdr.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240!\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=48600, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2096bdb000
mmap(NULL, 2143832, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2095cb5000
mprotect(0x7f2095cc0000, 2093056, PROT_NONE) = 0
mmap(0x7f2095ebf000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xa000) = 0x7f2095ebf000
close(3)                                = 0
open("/usr/lib64/libconfig++.so.9", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20\211\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=81208, ...}) = 0
mmap(NULL, 2176472, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2095aa1000
mprotect(0x7f2095ab4000, 2093056, PROT_NONE) = 0
mmap(0x7f2095cb3000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x12000) = 0x7f2095cb3000
close(3)                                = 0
open("/usr/lib64/libfftw3f.so.3", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20\312\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1560408, ...}) = 0
mmap(NULL, 3656592, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2095724000
mprotect(0x7f2095895000, 2093056, PROT_NONE) = 0
mmap(0x7f2095a94000, 53248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x170000) = 0x7f2095a94000
close(3)                                = 0
open("/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\271\5\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=995368, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2096bda000
mmap(NULL, 3176096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f209541c000
mprotect(0x7f2095505000, 2097152, PROT_NONE) = 0
mmap(0x7f2095705000, 40960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe9000) = 0x7f2095705000
mmap(0x7f209570f000, 83616, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f209570f000
close(3)                                = 0
open("/lib64/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 U\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1042648, ...}) = 0
mmap(NULL, 3137880, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f209511d000
mprotect(0x7f209521b000, 2093056, PROT_NONE) = 0
mmap(0x7f209541a000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xfd000) = 0x7f209541a000
close(3)                                = 0
open("/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300*\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=88328, ...}) = 0
mmap(NULL, 2184288, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2094f07000
mprotect(0x7f2094f1c000, 2093056, PROT_NONE) = 0
mmap(0x7f209511b000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x14000) = 0x7f209511b000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\306\10\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1627936, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2096bd9000
mmap(NULL, 3735128, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2094b77000
mprotect(0x7f2094cfe000, 2093056, PROT_NONE) = 0
mmap(0x7f2094efd000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x186000) = 0x7f2094efd000
mmap(0x7f2094f03000, 15960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f2094f03000
close(3)                                = 0
open("/usr/lib64/libvorbis.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\2208\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=158360, ...}) = 0
mmap(NULL, 2253592, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2094950000
mprotect(0x7f2094976000, 2093056, PROT_NONE) = 0
mmap(0x7f2094b75000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x25000) = 0x7f2094b75000
close(3)                                = 0
open("/usr/lib64/libogg.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\33\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=22648, ...}) = 0
mmap(NULL, 2117960, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f209474a000
mprotect(0x7f209474f000, 2093056, PROT_NONE) = 0
mmap(0x7f209494e000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7f209494e000
close(3)                                = 0
open("/lib64/libusb-1.0.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0pB\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=84832, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2096bd8000
mmap(NULL, 2180368, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2094535000
mprotect(0x7f2094549000, 2093056, PROT_NONE) = 0
mmap(0x7f2094748000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x13000) = 0x7f2094748000
close(3)                                = 0
open("/lib64/libudev.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=75848, ...}) = 0
mmap(NULL, 79952, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2096bc4000
mprotect(0x7f2096bd5000, 4096, PROT_NONE) = 0
mmap(0x7f2096bd6000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x11000) = 0x7f2096bd6000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2096bc3000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2096bc2000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2096bc0000
arch_prctl(ARCH_SET_FS, 0x7f2096bc0740) = 0
mprotect(0x7f2094efd000, 16384, PROT_READ) = 0
mprotect(0x7f20960d6000, 4096, PROT_READ) = 0
mprotect(0x7f20969fe000, 4096, PROT_READ) = 0
mprotect(0x7f2096bd6000, 4096, PROT_READ) = 0
mprotect(0x7f2094748000, 4096, PROT_READ) = 0
mprotect(0x7f209494e000, 4096, PROT_READ) = 0
mprotect(0x7f209541a000, 4096, PROT_READ) = 0
mprotect(0x7f2094b75000, 4096, PROT_READ) = 0
mprotect(0x7f209511b000, 4096, PROT_READ) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2096bbf000
mprotect(0x7f2095705000, 32768, PROT_READ) = 0
mprotect(0x7f2095a94000, 49152, PROT_READ) = 0
mprotect(0x7f2095cb3000, 4096, PROT_READ) = 0
mprotect(0x7f2095ebf000, 4096, PROT_READ) = 0
mprotect(0x7f20962ea000, 4096, PROT_READ) = 0
mprotect(0x7f2096526000, 4096, PROT_READ) = 0
mprotect(0x7f20967e0000, 98304, PROT_READ) = 0
mprotect(0x608000, 4096, PROT_READ)     = 0
mprotect(0x7f2096c20000, 4096, PROT_READ) = 0
munmap(0x7f2096bdd000, 270010)          = 0
set_tid_address(0x7f2096bc0a10)         = 31944
set_robust_list(0x7f2096bc0a20, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7f2095ec6b34, [], SA_RESTORER|SA_SIGINFO, 0x7f2095ed0cb0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f2095ec6bac, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f2095ed0cb0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
futex(0x7f2095721b0c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f2095721b18, FUTEX_WAKE_PRIVATE, 2147483647) = 0
brk(0)                                  = 0x2422000
brk(0x2443000)                          = 0x2443000
open("/usr/local/etc/rtl_airband.conf", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0600, st_size=7842, ...}) = 0
fstat(3, {st_mode=S_IFREG|0600, st_size=7842, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2096c1e000
read(3, "# Sample RTLSDR_Airband configur"..., 8192) = 7842
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f2096c1e000, 4096)            = 0
futex(0x7f209511c1d0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(2, "Error while parsing configuratio"..., 39Error while parsing configuration file ) = 39
write(2, "/usr/local/etc/rtl_airband.conf", 31/usr/local/etc/rtl_airband.conf) = 31
write(2, " line ", 6 line )                   = 6
write(2, "284", 3284)                      = 3
write(2, ": ", 2: )                       = 2
write(2, "syntax error", 12syntax error)            = 12
write(2, "\n", 1
)                       = 1
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by szpajder** [comment]
Oops, the example config is broken. Please delete the comma at the end of line 283.

I'll push a fix in a moment.

**Comment by M0CRT** [comment]
:-) Thanks!
