### ISSUE TITLE
Compatibility question!

### ISSUE THREAD

**Issue by SA7BNT** [szpajder/RTLSDR-Airband#131]
Hallo,
will the Pluto run with RTLSDR-Airband? 
Up to 20 MHz of instantaneous bandwidth should be nice ;)
[https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/adalm-pluto.html#eb-overview](url)

Best
Tim

**Comment by szpajder** [comment]
There is a SoapySDR driver for it (https://github.com/pothosware/SoapyPlutoSDR). If it works, then rtl_airband should work as well. Be a pioneer - try it out and share your experience :)

**Comment by SA7BNT** [comment]
I will order one and let you know about the result.
Thanks for info.

**Comment by starvald** [comment]
Internally it may be able to receive 20MHz but trying from personal experience it isn't much better than an rtl-sdr, pushing that much data through the usb2 interface it can't handle it without dropping samples.

**Comment by SA7BNT** [comment]
Well absolut right. Via USB no chance, but what with Network? Why are they making so manny nice hacks? ;)
https://wiki.analog.com/university/tools/pluto/users/customizing
https://hackaday.com/2019/05/10/pluto-sdr-goes-ethernet/
