### ISSUE TITLE
Squelch behaviour in scan mode

### ISSUE THREAD

**Issue by J-Luc16** [szpajder/RTLSDR-Airband#138]
Hi,

Thanks for this piece of software which is excellent. One PI3 with 2 dongles replaces a PC + 2 receivers for 1/5 of electricity consumption.

I have a small request : in "scan" mode, sometimes the squelch opens just before the scanner continues it's job, sending a slice of sound, half a word for example. It's not very nice to hear. It's not a matter of speed or something else, just avoiding to send bits of sound.

would it be possible to keep the channel quiet until the decision "stay on this frequency" is taken ?

Thanks a lot.
J-Luc

https://www.liveatc.net/search/?icao=lfbu

**Comment by szpajder** [comment]
Current scanning implementation is quite simplistic - the coupling between the scanner and the squelch is very loose and the effect you are seeing is one of it's drawbacks. In order to get this fixed, the whole thing essentially needs to be replaced with a better implementation, so it's not something which can be done in 5 minutes.

**Comment by J-Luc16** [comment]
Okay, understood.

Have a nice WE.
J-Luc F1JEK

**Comment by J-Luc16** [comment]
Even a little bit more delay before restart the scanner is hard ? ;-)

**Comment by szpajder** [comment]
There is currently no configuration knob for this, but you may modify `controller_thread()` routine a bit to get the effect you want. It's in `rtl_airband.cpp`, around line 135:

```C
                        if(consecutive_squelch_off < 10) {
(...)
                        if(consecutive_squelch_off == 10) {
```

Squelch restart can be delayed by increasing these values, in about 0.2sec increments, so 10 translates to about 2 seconds.

**Comment by J-Luc16** [comment]
Thanks a lot, boss ;-)

**Comment by J-Luc16** [comment]
Modified, compiled, installed, and works like a charm. I have not tried to understand what I have modified and why I had 2 lines to modify ;-) (I am used to develop under .NET for my job).

Thanks a lot.
J-Luc F1JEK
