### ISSUE TITLE
mp3 stream active but no sound

### ISSUE THREAD

**Issue by olyair11** [szpajder/RTLSDR-Airband#139]
Hello.
I am running the program on a Debian 9 server for some time.
Occasionally and on different channels and devices I have no sound in the streams
although there is activity. Recording the stream I can see activity in Audacity.
Exporting the file unmutes the sound.
Please advise. Recorded sample file (1minute) link is:
https://drive.google.com/file/d/1p9g_f3R-i8PCHLSglpjoDw8y4jmleDtg/view?usp=sharing
TIA

**Comment by szpajder** [comment]
> Occasionally and on different channels and devices I have no sound in the streams although there is activity.

It's hard to guess without seeing your config file.

> Recording the stream I can see activity in Audacity.

Do you record using rtl_airband's file output or by some other means?

> Exporting the file unmutes the sound.

What is "exporting the file"? rtl_airband does not have such a feature.

The file you posted does not look like it has been recorded with rtl_airband.

**Comment by olyair11** [comment]
To record the stream I am using the "file" output of rtl_airband along with the icecast connection.

> 

   mixer4: {
    outputs: (
        {
	  type = "icecast";
	  server = "123.34.56.78";
          port = 10801;
          mountpoint = "rodos.mp3";
          name = "Rodos Radar";
          username = "xxx";
          password = "yyy";
	},
	{
          type = "file";
          directory = "/usr/backup/rtl_airband/recordings/rodos";
          filename_template = "rodosf";
	  continuous = false;
	  append = true;
        }
    );
  } 

> 

"exporting the file"  I mean with Audacity, unmuted the sound. Please confirm.

The issue does not change if recording with rtl_airband continuously.
Listening to icecast stream has no sound.
Recording the icecast stream has the same issue as recording with rtl_airband.

**Comment by szpajder** [comment]
> To record the stream I am using the "file" output of rtl_airband along with the icecast connection.

Not enough information. Please post the whole config, ie. with "devices" and "mixers" sections.

> "exporting the file" I mean with Audacity, unmuted the sound. Please confirm.

Indeed, there is sound in the mp3 file that you posted. However I'm not sure if I fully understand how this file has been produced. You took the file recorded by rtl_airband from /usr/backup/rtl_airband/recordings/rodos/rodosf*.mp3, opened it in Audacity and exported as MP3? Is that what you have done? Or is it a recording of the rodos.mp3 Icecast stream?

> The issue does not change if recording with rtl_airband continuously.
> Listening to icecast stream has no sound.
> Recording the icecast stream has the same issue as recording with rtl_airband.

So it means rtl_airband produces absolutely no sound on any output. Correct?

Where does the audio from the rodosf_29-10-2019_10Z.mp3 file comes from then?

**Comment by szpajder** [comment]
OK, so the recording you posted comes from rodosf, which in turn comes from mixer4, which has 126.125 in the right channel and 133.325 in the left. There is audio present in the left channel, the right one is silent, but there is a short click in the beginning which indicates that the mixer is working, but after that there is only silence, so the squelch on 126.125 is probably closed all the time. Correct?

Was the audio on Icecast stream rodos.mp3 any different compared to the recording you posted? Did you have audio at that time in the left channel on Icecast?

I assume that all your Icecast outputs have connected to the server successfully. Please check your logs and verify this.

**Comment by olyair11** [comment]
>so the squelch on 126.125 is probably closed all the time. Correct?
>
Yes, this frequency was not used at that time, controllers are not using both at the same time.
I am sure because I am monitoring the channels with another receiver/scanner.
>Was the audio on Icecast stream rodos.mp3 any different compared to the recording you posted? 
>
Recorded icecast stream similarly had no sound.
> Did you have audio at that time in the left channel on Icecast?
>
No. I was listening to Icecast, no sound, while listening at the same time to the scanner was ok, in fact pretty loud and clear. This is why I started worrying... and took recordings on rtl_airband.

Rtl_airband logging in daemon.log and syslog shows all sources successfully connected to Icecast (2.4.3), same info in systemctl status. Icecast error.log is empty.

**Comment by szpajder** [comment]
> No. I was listening to Icecast, no sound, while listening at the same time
> to the scanner was ok, in fact pretty loud and clear. This is why I started
> worrying... and took recordings on rtl_airband.
>

So you have added a file output to mixer4 to take a recording from mixer4
and found that the recorded audio is fine, correct?

And at the same time the audio sent to the icecast output of mixer4 was
different (silent)?

This is not possible from theoretical standpoint - rtl_airband produces a
single stream of audio samples for all outputs attached to a particular
channel or mixer. Any differences that may arise here are related to:

- whether MP3 compression is enabled or not (icecast and file outputs are
compressed, while pulse outputs aren't)
- whether "continuous" flag is set on file output (if it's disabled, then
the output is not fed when squelch is closed).

So far I'm not convinced if it's really an issue with rtl_airband rather
than, eg. with the stream player (for example you might be listening to
something else than you think you do or you might have channel balance set
incorrectly, etc).

**Comment by olyair11** [comment]
Sorry Tomasz,  seems I confused you. Thanks for coming back to troubleshoot my issue.
>So you have added a file output to mixer4 to take a recording from mixer4
and found that the recorded audio is fine, correct?
And at the same time the audio sent to the icecast output of mixer4 was
different (silent)?
>
No. Recorded rtl_airband mixer4 in the file was silent, as well as the Icecast listening at the same time,
while listening to the scanner was loud on 133.325 that I was monitoring at the same time.
As you said it could not be otherwise. I have posted the rtl_airband recorded mixer4 which
shows that 133.325 was really active but somehow the sound is muted.
I wonder how Audacity rebuilt the file. Looks like it found recoverable errors ?

One more information I have found today with the scanner, is that the exact center frequency
is 133.327MHz, not 133.325MHz that is assigned in rtl_airband configuration.
Despite that difference the stream is recorded but somehow muted.

**Comment by szpajder** [comment]
>  I have posted the rtl_airband recorded mixer4 which shows that 133.325
> was really active but somehow the sound is muted.
> I wonder how Audacity rebuilt the file. Looks like it found recoverable
> errors ?
>
Can you post the original file recorded by rtl_airband then?


> One more information I have found today with the scanner, is that the
> exact center frequency
> is 133.327MHz, not 133.325MHz that is assigned in rtl_airband
> configuration.
>
Such a small difference should not be an issue.

**Comment by olyair11** [comment]
Posted file is the original mixer4 recording. I understand you confirmed that
there is sound in this file but is muted when you play it.

**Comment by szpajder** [comment]
> Posted file is the original mixer4 recording. I understand you confirmed
> that
> there is sound in this file but is muted when you play it.
>

It's not muted.  I tried it both with Audacity and VLC - it plays fine in
both apps and I can hear the audio in the left channel.

Is your audio equipment wired correctly?

**Comment by olyair11** [comment]
I am posting original mixer4 recording file again, because I verified that is muted with two different computers, while I can listen to other media files perfectly.
https://drive.google.com/file/d/1p4InXlmyuXilV_AvgA6VjumD0DiHDLtE/view?usp=sharing
Sorry, please check again.

**Comment by danmilon** [comment]
The left channel has proper ATC audio. The right channel doesn't contain any ATC audio, only the initial "click" sound.

Here's a screenshot from audacity:

![ss](https://user-images.githubusercontent.com/1139595/67855763-bcb24800-fb1b-11e9-926c-d039a1c39931.jpg)

**Comment by szpajder** [comment]
Sorry, please check again.
>
I checked again and it plays OK. Maybe I should record a video as a proof?
;-)

What app are you using to play this?

Have you verified your mixer settings? Maybe a particular player instance
is muted in the mixer or has balance set to the far right, so that you
can't hear the left channel?

If you are on Windows, please make sure that you have disabled all the
Bang-Olufsen-Karman-Hardon-audio-experience improvers, because they tend to
give surprises. Right now I'm at Win10 workstation and I found that the
audio in your file is just slightly left of center instead of full left.
Apparently there was some kind of speech improvement algo turned on in
audio settings. Once I have disabled this great feature, I can now hear the
audio full-left, as expected. Who knows what kind of audio improvements you
may have.

**Comment by olyair11** [comment]
Strange...  :-(  sorry for confusion.
I can not hear sound, except the "click", with Audacity 2.1.3 on Windows 7,
although the left playback level meter shows up to almost 0 dB.
I will check for peculiar settings and come back...

**Comment by olyair11** [comment]
Tomasz, you were right. 
After some fighting... with windows drivers/audio settings I found that my speaker's
left channel only! was muted. I reinstalled sound card drivers and disabled
all enhancements/improvements. Both channels now are back to normal. :-)
I was confused when testing on another computer, where by coincidence, there was
a cabling problem to its speakers, only right channel working :-(  too.
Please forgive my noob reporting and consider the issue as not existing,
maybe I should delete it. Thanks for helping.

**Comment by szpajder** [comment]
Glad you found the cause.

No need to be sorry and no need to delete anything. Every issue with a solution might be valuable to others too!
