### ISSUE TITLE
Wideband FM radio support.

### ISSUE THREAD

**Issue by atymic** [szpajder/RTLSDR-Airband#147]
Hey :)

Just wondering if there are any plans to support this?
I'm a RF noob, and didn't realise it wasn't support, but your software is awesome.

Thanks!

**Comment by szpajder** [comment]
The current channelizer implementation is designed to work with narrowband channels only, so no, this is not possible as of now.

**Comment by atymic** [comment]
No worries. Thanks for the response. Awesome project regardless!
