### ISSUE TITLE
[Question] listening to approach or ATIS on demand

### ISSUE THREAD

**Issue by rvt** [szpajder/RTLSDR-Airband#148]
hey,

is it possible to externally trigger airband to listen to a frequency (for example ATIS)  for a number of seconds but when done it will scan approach/tower?

Or by other means, externally control hairband to control what frequencies to scan..

**Comment by szpajder** [comment]
Nope, the only way of controlling the program is via config file.

**Comment by rvt** [comment]
Thans for the quick responsie.
