### ISSUE TITLE
Wiki documentation missing for several scan options

### ISSUE THREAD

**Issue by charlie-foxtrot** [szpajder/RTLSDR-Airband#154]
"scan" mode supports Channel configuration parameters for `labels` and `squelch` that are missing from the Wiki

**Comment by szpajder** [comment]
https://github.com/szpajder/RTLSDR-Airband/wiki/Icecast-metadata-updates-in-scan-mode
https://github.com/szpajder/RTLSDR-Airband/wiki/Manual-squelch-setting

**Comment by charlie-foxtrot** [comment]
yep, sure enough ;)

maybe add a link from https://github.com/szpajder/RTLSDR-Airband/wiki/Configuring-channels-for-scan-mode

**Comment by szpajder** [comment]
It's basically the same thing as in https://github.com/szpajder/RTLSDR-Airband/issues/153
