### ISSUE TITLE
Pls add hackRF

### ISSUE THREAD

**Issue by ah1102** [szpajder/RTLSDR-Airband#165]
please add other devices, for example, hackRF, which are also very common

**Comment by starvald** [comment]
hackrf is supported by soapysdr.
https://github.com/pothosware/SoapyHackRF/wiki

if you enable building rtlsdr_airband with soapy it should work.

**Comment by ah1102** [comment]
Thanks!

**Comment by rapbando** [comment]
> Thanks!

Did you manage to get it recognized by rtl_airband?
