### ISSUE TITLE
Add notch to scan mode

### ISSUE THREAD

**Issue by poblabs** [szpajder/RTLSDR-Airband#176]
[As mentioned here](https://github.com/szpajder/RTLSDR-Airband/issues/171#issuecomment-668845122), I'm looking to see if we can add notch to scan mode since I'm using scanning instead of multimode. 

Thanks!

**Comment by charlie-foxtrot** [comment]
@poblabs can you try #183

**Comment by poblabs** [comment]
Will do! I'll let it run overnight.

**Comment by poblabs** [comment]
So far so good, thanks again!
