### ISSUE TITLE
Bypass of "Automatic Volume Equalization".

### ISSUE THREAD

**Issue by vesis84** [szpajder/RTLSDR-Airband#178]
Hi Szpajder, thank you for the project.
We use it to record an audio database for speech recognition training, and we are using the 'raw' output in IQ format .

I'd like to ask.  Could you expose a bypass of "Automatic Volume Equalization"
into a config file? (or show where it is in the code...) 

It was mentioned that it exists in the code in here: 
https://github.com/szpajder/RTLSDR-Airband/issues/73

I know that silent parts will be lost, but we can live with that...

With kind regards,
Karel

Btw: Is the 'raw' output signal in IQ format affected by 'Automatic Volume Equalization' ? We use 'csdr' demodulate it to 'wav' and then convert to 'flac'. I found this line https://github.com/szpajder/RTLSDR-Airband/blob/master/rtl_airband.cpp#L559 that modifies the `iq_in` with some values from look-up table... So, i guess, the 'Automatic Volume Equalization' is not applied to IQ signal. Is this correct?

**Comment by szpajder** [comment]
Correct. This feature does not apply to rawfile outputs.
