### ISSUE TITLE
Unable to install RTLSDR Library

### ISSUE THREAD

**Issue by Skyboy54** [szpajder/RTLSDR-Airband#18]
When I follow the instructions for installing the RTLSDR library, I get this error for autoreconf:
pi@raspberrypi ~/rtl-sdr $ autoreconf -i
src/Makefile.am:10: Libtool library used but `LIBTOOL' is undefined
src/Makefile.am:10:   The usual way to define `LIBTOOL' is to add `LT_INIT'
src/Makefile.am:10:   to `configure.ac' and run `aclocal' and `autoconf' again.
src/Makefile.am:10:   If `LT_INIT' is in `configure.ac', make sure
src/Makefile.am:10:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

How can I make this work?  I am a Raspberry newbie.  Thank you.

**Comment by szpajder** [comment]
Probably you don't have libtool installed.

Just run: "sudo apt-get install libtool".
