### ISSUE TITLE
re: add bandwidth filter using a lowpass after removing phase rotation 

### ISSUE THREAD

**Issue by starvald** [szpajder/RTLSDR-Airband#187]
saw this has been added to unstable.
what is it? and if i think its useful to me how do i use it?

**Comment by szpajder** [comment]
It's a bandpass filter which cuts down the channel bandwidth to a specified value. Might be useful if adjacent channels are causing interference to your channel of interest.

Just add `bandwidth = <value_in_hz>` to the channel definition.

**Comment by starvald** [comment]
ok thanks.
