### ISSUE TITLE
RTL_AIRBAND_VERSION Incorrect

### ISSUE THREAD

**Issue by Staja** [szpajder/RTLSDR-Airband#199]
`RTL_AIRBAND_VERSION` in [rtl_airband.h](https://github.com/szpajder/RTLSDR-Airband/blob/v3.2.1/rtl_airband.h#L43) doesn't match tagged release.

**Comment by szpajder** [comment]
Well, that's embarrasing ;) Thanks, I'll fix that in the next release.
