### ISSUE TITLE
Device index

### ISSUE THREAD

**Issue by leifskaue** [szpajder/RTLSDR-Airband#26]
If several dongles are connected, will they be given a completely random index at each boot? Is it possible to assign them by serial?

I'm thinking of a situation where you have two or more dongles that have different freq correction or are connected to different types of antennas.

**Comment by szpajder** [comment]
The index order will be the same on each boot, as long as you keep the
hardware configuration unchanged. Replugging the dongles to different
ports, adding/removing USB host controllers, etc. will cause the indexes to
change.

rtl_airband does not currently support device assignment by serial number.
You can check the index -> serial mapping with rtl_test tool, which comes
with librtsdr.
