### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amane93** [szpajder/RTLSDR-Airband#263]
**Describe your environment**

  - RTLSDR-Airband version you are using (**release 3.2.0**):
  - `make` options used to build the program: **PLATFORM=x86 make**	
  - Hardware platform (**x64**):
  - Operating system name and version: **ubuntu 16**

What happened? : **Rtl_airband doesnt not close rtl dongle on program exit, dongle cant be accessed and heats up.**

What you expected to happen? **For rtl_airband to exit properly**

Steps to Reproduce **install 3.2.0 and after running rtl_airband run the command again**

**Additional context**
Add any other relevant information about the problem here.
After exiting program dongle heats up. have to physically disconnect usb. 

**Your rtl_airband.conf file**
devices:
({
 type = "rtlsdr";
 index = 0;
 gain = 25;
 correction = 80;
 mode = "scan";
 channels:
 ( {
  freqs = (94.0, 106.2);
  squelch = 35;
   outputs: (
  {
    type = "icecast";
    server = "icecast.server.example.org";
    port = 8080;
    mountpoint = "TWR.mp3";
    name = "fmradio-r"; 
    genre = "Songs"; 
    username = "source";
    password = "mypassword";
  },
  {  type = "file";
   directory = "/home/..../Recordings";
   filename_template = "fmRadio";
  }
 );
 }
 );
 }
);

**Comment by szpajder** [comment]
Whenever the program receives a stopping signal (SIGHUP, SIGINT, SIGQUIT or SIGTERM) it stops all devices before exiting. It works for me.

Perhaps you are SIGKILLing it?
