### ISSUE TITLE
Please explain how to read the textual waterfalls

### ISSUE THREAD

**Issue by brantel** [szpajder/RTLSDR-Airband#36]
Maybe I missed it but I can't find any documentation on how to interpret the textual waterfalls.

Please point me in the right direction.

**Comment by spotter-ssol** [comment]
Here: https://github.com/szpajder/RTLSDR-Airband/issues/8#issuecomment-207935532

**Comment by brantel** [comment]
Thanks for the reply!

So the first number is the signal level the second the noise floor.
What does the * represent?  

Thanks again!

**Comment by spotter-ssol** [comment]
The * means squelsh open.
