### ISSUE TITLE
"send_scan_freq_tags" not working inside a mixer

### ISSUE THREAD

**Issue by spotter-ssol** [szpajder/RTLSDR-Airband#45]
I'm redirecting the output of a scan into a mixer called "mixer2", but "send_scan_freq_tags" has no effect.

       mixer2: {
                outputs: (
                        {
                        disable = false;
                        type = "icecast";
                        server = "127.0.0.1";
                        port = 8000;
                        mountpoint = "scan";
                        name = "ATC SCAN"
                        genre = "ATC";
                        username = "source";
                        password = "*****";
                        send_scan_freq_tags = true;
                        ...

**Comment by szpajder** [comment]
Yes, this is intentional. Mixers mix audio, not metadata.
