### ISSUE TITLE
[Suggestion] display manual squelch level on waterfall

### ISSUE THREAD

**Issue by spotter-ssol** [szpajder/RTLSDR-Airband#54]
Just a suggestion: with squelch set to auto, the second field on waterfall displays the current noise floor (AFAIK). When using manual squelch, that field always shows "100". I think it would be interesting to have the channels' manual squelch level in that field.

**Comment by szpajder** [comment]
This is now implemented in unstable branch. Sorry for delay.

**Comment by spotter-ssol** [comment]
Thanks! I'm eager to compile and test it. I'm also saw that there are some improvements in the code, like per channel squelch (AFAIK). Do we need to modify anything in the config file to use this feature?

**Comment by szpajder** [comment]
Auto squelch per scanned channel is enabled by default. It is also possible
to set squelch manually per scanned channel, however this should hardly
ever be necessary in practice. There is an example of the new squelch
syntax in config/reference.conf. See also
https://github.com/szpajder/RTLSDR-Airband/issues/61 .

**Comment by spotter-ssol** [comment]
Tested & working! Thanks to all of you!
