### ISSUE TITLE
Documentation: 16M GPU memory will not work

### ISSUE THREAD

**Issue by bluepup** [szpajder/RTLSDR-Airband#58]
Please document that 16M of GPU memory (tested on RPI1) will result in termination of the process after a message like "Found Rafael Micro R820T tuner" nothing else will be written either to stderr or /var/log/messages

**Comment by szpajder** [comment]
Currently README.md mentions that setting gpu_mem to anything lower than 64
MB will cause the program to fail with an error message "Unable to enable
V3D. Please check your firmware is up to date". Maybe your syslog
configuration discards this message or directs it to a different log file
than the one you think it should?
