### ISSUE TITLE
Scanner mode mixed modulation

### ISSUE THREAD

**Issue by kuntakinte1** [szpajder/RTLSDR-Airband#72]
"Scanner mode - decode unlimited number of AM and/or NFM channels with frequency hopping in a round-robin fashion (no frequency range limitations)"

I can see this, but can't find any example how to use scanning with different modulations. I alredy tried two section of "freqs", two sections of "channels" and it's always an error.

**Comment by szpajder** [comment]
It's not supported. Right now the modulation is common to all channels scanned on a particular receiver.

**Comment by kuntakinte1** [comment]
"AM and[...] NFM" is not true then.

**Comment by szpajder** [comment]
Release 2.4.0 includes clarified documentation.
Closing.
