### ISSUE TITLE
Suggest edit of Readme

### ISSUE THREAD

**Issue by radiostationx** [szpajder/RTLSDR-Airband#77]
Suggestion for edits of the readme file,
Using here v2.4.0 as example.

To obtain the latest build v2.4.0 within the command line 

`sudo wget https://github.com/szpajder/RTLSDR-Airband/archive/v2.4.0.tar.gz`

then to unpack this

`tar xvfz v2.4.0.tar.gz`

then change to directory

` cd RTLSDR-Airband-2.4.0`

and proceed with make & install instructions from readme.md

Thanks to szpajder for his work on this.

**Comment by szpajder** [comment]
There is a new user's manual now available on the [wiki](https://github.com/szpajder/RTLSDR-Airband/wiki), which has this suggestion included.

Closing, thanks.
