### ISSUE TITLE
untidy close

### ISSUE THREAD

**Issue by nzstevem** [szpajder/RTLSDR-Airband#80]
Hi, if I run airband interactively and terminate the program by a control-Z (EOF) to the keyboard the rtlsdr device is not released cleanly and the program can not be restarted without rebooting the system.

Terminating the program with a control-C triggers a clean exit. 

Rgds

**Comment by szpajder** [comment]
It's because ctrl+Z does not kill the process, but stops it :-) It still
exists and occupies the device.

**Comment by szpajder** [comment]
Closing, as it's not a bug.
