### ISSUE TITLE
Squelch bug?

### ISSUE THREAD

**Issue by spotter-ssol** [szpajder/RTLSDR-Airband#84]
I've got this strange behavior regarding manual squelch levels:
<a href="http://imgbox.com/EWQ9hoym" target="_blank"><img src="https://images2.imgbox.com/29/ee/EWQ9hoym_o.png" alt="image host"/></a>
Even after the end of transmission and manual squelch level up to 4x the noise floor, audio keeps streaming indefinitely. This is how it look like in Audacity:
<a href="http://imgbox.com/WjhdH3y3" target="_blank"><img src="https://images2.imgbox.com/fc/b2/WjhdH3y3_o.png" alt="image host"/></a>
After some testing I've discovered that this behavior only occurs when compiled without NFM support.

**Comment by szpajder** [comment]
Yep, it's broken. Check out the current unstable branch - should be OK now.

**Comment by spotter-ssol** [comment]
Solved! Thanks!

**Comment by spotter-ssol** [comment]
Today I was testing some configs and got the same behaviour, but now in **scan mode**. Maybe the same bug on another portion of code related to scan?
<a href="http://imgbox.com/SVJf5J7e" target="_blank"><img src="https://images2.imgbox.com/21/6d/SVJf5J7e_o.png" alt="image host"/></a>

**Comment by szpajder** [comment]
Do you have any reliable way of reproducing this problem? Does it happen very often?

I've tried several configs, various bands, signal strengths and squelch settings, but it never happened to me so far.

**Comment by spotter-ssol** [comment]
I did some more testing and discovered that this happens very often (both multichanel and scan) when I set the squelch 3x (or less) the noise floor level. Audio keeps streaming for about 5 to 15 seconds then usually closes itself. When squelch is set 4x or higher this problem virtually disapears.

**Comment by WeKnowMC** [comment]
I have also been experiencing this problem occasionally. It seems like it is most apparent when listening to weak signals, which sometimes dip in and out of the squelch - but it doesn't happen enough for me to reliably confirm this.

**Comment by szpajder** [comment]
Please check the current code from unstable branch. I have applied a small tweak, and now it should behave better.

**Comment by spotter-ssol** [comment]
Tested with squelch as low as 2x times the noise floor and no sign of problems. Now I can properly track weak signals.
Thank you, sir. I'm having A LOT of fun with this software. Your work is much appreciated!
