### ISSUE TITLE
Sequential mixing of simultaneous multimode channels?

### ISSUE THREAD

**Issue by edbir1** [szpajder/RTLSDR-Airband#89]
This is probably more of a support question, but can rtlsdr_airband do time delay mixing of multiple channels?  

I am thinking of what SDRtrunk does when streaming a trunking system with multiple channels simultaneously transmitting.  It decodes and buffers multiple transmissions simultaneously and streams them sequentially by finish time until the buffer is empty or fills up to X.

I am trying to stream a low usage rural NFM analog system whose frequencies are generally close together, so multimode is perfect, but when there is traffic, there often is traffic on all the frequencies at the same time.  It would be nice to combine sheriff, fire, rescue and EMS into one sequential stream during activity, rather than having multiple low use streams.  If I were to use scan mode, then I miss the traffic on all the other channels.

**Comment by szpajder** [comment]
There is no such feature right now and it does not look like something
which can be done in 10 minutes.

Stereo mixing is good for this purpose. Put the first channel in the left
ear, second one in right ear and third one centered. It's pretty easy to
focus on a particular channel when they are stereo-separated (at least for
me) and you won't miss a thing. Here is how to configure it:
https://github.com/szpajder/RTLSDR-Airband/wiki/Configuring-mixers

You can also record everything to files and review recordings one by one
later.
