### ISSUE TITLE
Can´t compile

### ISSUE THREAD

**Issue by evertonma** [szpajder/RTLSDR-Airband#9]
Hello

When I try to compile the application, I get the following message:

<code>~/RTLSDR-Airband $ make rtl_airband_neon
make -C hello_fft
make[1]: Entering directory '/home/pi/RTLSDR-Airband/hello_fft'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/RTLSDR-Airband/hello_fft'
g++ -L/opt/vc/lib  rtl_airband_neon.o rtl_airband.o hello_fft/hello_fft.a  -lrt -lm -lvorbisenc -lmp3lame -lshout -lpthread -lrtlsdr -lbcm_host -o rtl_airband_neon
g++: error: hello_fft/hello_fft.a: No such file or directory
<builtin>: recipe for target 'rtl_airband_neon' failed
make: *** [rtl_airband_neon] Error 1</code>

RPI2, Linux raspberry 4.1.8-v7+, RTLSDR-Airband cloned from https://github.com/szpajder/RTLSDR-Airband/

Can anyone help me?

**Comment by szpajder** [comment]
Could you please do the following:

    cd /home/pi/RTLSDR-Airband
    git status
    git remote -v
    git rev-parse HEAD

And paste the output?
